app/models/job.rb
app/models/match.rb
app/models/user.rb
config/initializers/devise.rb
config/routes.rb
db/migrate/20181112151635_devise_create_users.rb
db/migrate/20181112151648_create_jobs.rb
db/migrate/20181112151835_create_matches.rb
db/schema.rb
test/models/job_test.rb
test/models/match_test.rb
test/models/user_test.rb

models and migrations

---

app/controllers/jobs_controller.rb
app/controllers/matches_controller.rb
app/controllers/users_controller.rb
config/routes.rb
test/controllers/jobs_controller_test.rb
test/controllers/matches_controller_test.rb
test/controllers/users_controller_test.rb

Controllers for user, match and job

controllers updated

---

app/controllers/matches_controller.rb
app/models/user.rb
app/views/jobs/_form.html.erb
app/views/jobs/index.html.erb
app/views/jobs/new.html.erb
app/views/jobs/show.html.erb
app/views/matches/_form.html.erb
app/views/matches/index.html.erb
app/views/matches/new.html.erb
app/views/matches/show.html.erb
app/views/users/_form.html.erb
app/views/users/index.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb

added basic views

---

app/views/matches/index.html.erb

Added if statements to only show parameters if they exist

matches updated with if statements

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/registrations/new.html.erb
app/views/jobs/edit.html.erb
app/views/jobs/show.html.erb
app/views/matches/_form.html.erb
app/views/matches/edit.html.erb
app/views/matches/show.html.erb
app/views/users/edit.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb
config/initializers/devise.rb
config/routes.rb

Devise implemented.
Views updated for basic CRUD

devise and all views

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/config/_colors.scss

navbar and colors changed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_navbar.scss
app/controllers/users_controller.rb
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb
app/views/users/search.html.erb
app/views/users/show.html.erb
config/routes.rb

Updated home page, routes, search bar, navbar and liks

home page and routes updated

---

.gitignore
Gemfile

Cloudinary

---

app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/registrations/deleted from edit
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/layouts/application.html.erb
app/views/shared/_flashes.html.erb
db/migrate/20181112151635_devise_create_users.rb
db/migrate/20181112151648_create_jobs.rb
db/schema.rb

migrations changed with more fields

---

app/assets/stylesheets/components/_navbar.scss

navbar before end removed

---

app/assets/stylesheets/components/_avatar.scss
app/views/users/index.html.erb
app/views/users/search.html.erb
app/views/users/show.html.erb

profile responsive

---

app/views/layouts/application.html.erb
app/views/shared/_navbar.html.erb

pulldown fixed and "L "removed

pulldown fixed

---

app/assets/stylesheets/pages/_user_index.scss
app/views/users/index.html.erb
app/views/users/search.html.erb

Experience removed from list view
fonts fixed

user card simplified

---

Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_user_index.scss
app/controllers/users_controller.rb
app/javascript/packs/map.js
app/models/user.rb
app/views/layouts/application.html.erb
app/views/users/index.html.erb
app/views/users/search.html.erb
config/initializers/geocoder.rb
config/webpack/environment.js
db/migrate/20181115102606_add_coordinates_to_users.rb
db/schema.rb
package.json
yarn.lock

maps have been added with markers

---

app/assets/stylesheets/components/_footer.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/users_controller.rb
app/views/pages/home.html.erb

Search bar with 2 fields and search button
reduced footer

search bar with 2 fields added and search button

---

app/assets/stylesheets/pages/_home.scss
app/javascript/packs/map.js
app/views/layouts/application.html.erb
app/views/pages/home.html.erb
package.json
yarn.lock

autocomplete finally works

---

config/environments/production.rb

added to production file to get heroku to accept the maps

mapbox on heroku

---

app/assets/stylesheets/pages/_profile.scss
app/controllers/jobs_controller.rb
app/controllers/matches_controller.rb
app/views/devise/registrations/edit.html.erb
app/views/jobs/_form.html.erb
app/views/matches/_form.html.erb
app/views/matches/index.html.erb
app/views/users/show.html.erb

Buttons changed and other small style changes

buttons and minor changes

---

app/javascript/packs/map.js

all search functions have auto complete now!

auto complete added to all search fields

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/controllers/users_controller.rb
app/views/shared/_navbar.html.erb
db/migrate/20181119140620_remove_messages_from_matches.rb
db/migrate/20181119140739_remove_duration_from_jobs.rb
db/migrate/20181119140810_add_end_date_to_jobs.rb
db/migrate/20181119141348_add_public_to_jobs.rb
db/migrate/20181119142537_add_company_to_user.rb
db/migrate/20181119143459_add_conversations_to_matches.rb
db/schema.rb

Search improved with area of influence
New migrations added.

search with radius and new migrations

---

app/controllers/reviews_controller.rb
app/views/users/show.html.erb

changed a few items in dashboard

---

app/views/users/show.html.erb

review changed

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_user_index.scss

changed font weight on all p tags

p tags font weight changed

---

app/views/users/show.html.erb

Modified all the modals on the show page. Now the text are clickable and they have default "Click here to add ..." if you are the user who's page you are on

all the modals of the profile page modified

---

app/assets/stylesheets/components/_banner.scss
app/views/matches/show.html.erb

small changes
